version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    container_name: postgres
