[project]
name = "twpatentdatabase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "einops>=0.8.1",
    "fastapi[standard]>=0.115.11",
    "marker-pdf>=0.2.17",
    "mypy>=1.15.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.10",
    "pydantic>=2.10.6",
    "pymilvus>=2.5.6",
    "python-dotenv>=1.0.1",
<<<<<<< HEAD
    "selenium>=4.29.0",
    "torchvision>=0.21.0",
=======
    "python-jose[cryptography]>=3.4.0",
    "rich>=14.0.0",
    "ruff>=0.9.10",
    "selenium>=4.29.0",
    "sentence-transformers>=4.0.1",
    "sqlalchemy>=2.0.40",
>>>>>>> c4c7251fad5d109f62c08b87cbf74d04147e4dbb
    "transformers>=4.49.0",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    #### modules
    "ANN",    # flake8-annotations
    "COM",    # flake8-commas
    "C90",    # mccabe complexity
    "DJ",     # django
    "EXE",    # flake8-executable
    "T10",    # debugger
    "TID",    # flake8-tidy-imports
    "FBT",
    "BLE001",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "E402",
    "E501",
    # "FA"
    "ERA001",
    "TRY003",
    "TD002",
    "TD003",
    "FIX002",
    "S106"
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
