# Code by AkinoAlice@TyrantRey


class AccessTokenError(Exception): ...


class InvalidAlgorithmError(AccessTokenError): ...


class InvalidJWTExpireTimeFormatError(AccessTokenError): ...


class InvalidUnsupportedJWTExpireTimeError(AccessTokenError): ...


class RefreshTokenExpiryError(AccessTokenError): ...


class InvalidTokenTypeError(AccessTokenError): ...
